# Generated by Django 5.1.4 on 2025-07-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_code', models.CharField(blank=True, max_length=5, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('rc_number', models.CharField(max_length=50, verbose_name='RC Number')),
                ('md_phone_number', models.CharField(max_length=20, verbose_name='MD Phone Number')),
                ('md_picture', models.ImageField(upload_to='md_pictures/', verbose_name='MD Picture')),
                ('national_first_registration_date', models.DateField(verbose_name='National First Registration Date')),
                ('certificate_issued_date', models.DateField(verbose_name='Certificate Issued Date')),
                ('certificate_expiration_date', models.DateField(verbose_name='Certificate Expiration Date')),
                ('enugu_first_registration_date', models.DateField(verbose_name='Enugu First Registration Date')),
                ('enugu_issued_date', models.DateField(verbose_name='Enugu Certificate Issued Date')),
                ('enugu_expiring_date', models.DateField(verbose_name='Enugu Certificate Expiring Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-created_at'],
            },
        ),
    ]
