# Generated by Django 5.1.4 on 2025-07-02 08:57

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_member_certificate_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['company_name']},
        ),
        migrations.RemoveField(
            model_name='member',
            name='enugu_first_registration_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='member',
            name='national_first_registration_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='rc_number',
        ),
        migrations.AddField(
            model_name='member',
            name='enugu_first_registered',
            field=models.DateField(blank=True, null=True, verbose_name='Date of First Registration (Enugu)'),
        ),
        migrations.AddField(
            model_name='member',
            name='national_first_registered',
            field=models.DateField(blank=True, null=True, verbose_name='Date of First Year Registered (National)'),
        ),
        migrations.AddField(
            model_name='member',
            name='rc_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='RC Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='certificate_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Certificate Expiry Date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='certificate_issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Certificate Issued Date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='certificate_picture',
            field=models.ImageField(blank=True, null=True, upload_to=portal.models.upload_certificate_picture, verbose_name='Certificate Picture'),
        ),
        migrations.AlterField(
            model_name='member',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='md_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MD Phone Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='md_picture',
            field=models.ImageField(blank=True, null=True, upload_to=portal.models.upload_md_picture, verbose_name='MD Picture'),
        ),
    ]
