# Generated by Django 5.1.4 on 2025-07-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_member_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_renewal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Renewal Date'),
        ),
        migrations.AddField(
            model_name='member',
            name='renewal_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Renewals'),
        ),
    ]
