# Generated by Django 5.1.4 on 2025-07-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_member_last_renewal_date_member_renewal_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('electricity', 'Electricity'), ('furnitures', 'Furnitures'), ('stationaries', 'Stationaries'), ('fuel_diesel', 'Fuel/Diesel'), ('salary', 'Salary'), ('events', 'Events'), ('exco8_meetings', 'Exco8 meetings hosting'), ('general_meeting', 'General meeting expenses'), ('logistics', 'Logistics'), ('outreach', 'Outreach/Social responsibility'), ('advertising', 'Advertising and publicity'), ('office_maintenance', 'Office maintenance'), ('office_equipments', 'Office equipments'), ('internet_subscription', 'Internet subscription'), ('miscellaneous', 'Miscellaneous')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('national_rebate', 'National rebate(registration)'), ('enugu_validation', 'Enugu validation fee'), ('donations', 'Donations'), ('other_sources', 'Other sources')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
