# Generated by Django 5.1.4 on 2025-07-04 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(help_text='e.g., State Chairman, Vice Chairman, etc.', max_length=255)),
                ('company_occupation', models.CharField(blank=True, help_text='Company or occupation details', max_length=500, null=True)),
                ('council_type', models.CharField(choices=[('state', 'State Executive'), ('zonal', 'Zonal Representative'), ('national', 'National Executive')], default='state', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='executives/')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within council type')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Executive Council Member',
                'verbose_name_plural': 'Executive Council Members',
                'ordering': ['council_type', 'order', 'name'],
            },
        ),
    ]
