# Generated by Django 5.1.4 on 2025-07-05 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_member_company_category_member_company_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('form_file', models.FileField(upload_to='forms/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Form Upload',
                'verbose_name_plural': 'Form Uploads',
                'ordering': ['-created_at'],
            },
        ),
    ]
