# Generated by Django 5.1.4 on 2025-07-07 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_secretaryadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='payer_member',
            field=models.ForeignKey(blank=True, help_text='Select member company for Enugu validation fees', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.member', verbose_name='Payer (Member Company)'),
        ),
        migrations.AddField(
            model_name='income',
            name='payer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payer Name'),
        ),
    ]
