# Generated by Django 5.1.4 on 2025-07-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_income_payer_member_income_payer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='company_category',
            field=models.CharField(blank=True, choices=[('building_development', 'Building Development'), ('site_and_services', 'Site and Services'), ('neighbourhood_estate', 'Neighbourhood Estate'), ('engineering_construction', 'Engineering/Construction'), ('surveying', 'Surveying'), ('contractor ', 'Contractor '), ('realtor ', 'Realtor '), ('student ', 'Student ')], max_length=50, null=True, verbose_name='Company Category'),
        ),
    ]
