# Generated by Django 5.1.4 on 2025-07-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20250708_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('electricity', 'Electricity'), ('furnitures', 'Furnitures'), ('stationaries', 'Stationaries'), ('fuel_diesel', 'Fuel/Diesel'), ('salary', 'Salary'), ('events', 'Events'), ('exco8_meetings', 'Exco8 meetings hosting'), ('general_meeting', 'General meeting expenses'), ('logistics', 'Logistics'), ('outreach', 'Outreach/Social responsibility'), ('advertising', 'Advertising and publicity'), ('office_maintenance', 'Office maintenance'), ('office_equipments', 'Office equipments'), ('website_maintenance', 'Website maintenance'), ('internet_subscription', 'Internet subscription'), ('miscellaneous', 'Miscellaneous')], max_length=50),
        ),
    ]
