# Generated by Django 5.1.4 on 2025-07-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_alter_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='company_category',
        ),
        migrations.AddField(
            model_name='member',
            name='company_categories',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Company Categories'),
        ),
    ]
