# Generated by Django 5.1.4 on 2025-07-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_remove_member_company_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='redan_reg_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='REDAN Reg. Number'),
        ),
    ]
