# Generated by Django 5.1.4 on 2025-07-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_member_redan_reg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='company_projects',
            field=models.TextField(blank=True, help_text="Describe your company's projects", null=True, verbose_name='Company Projects'),
        ),
        migrations.AddField(
            model_name='member',
            name='project_images',
            field=models.ImageField(blank=True, help_text='Upload project images', null=True, upload_to='project_images/', verbose_name='Project Images'),
        ),
    ]
