# Generated by Django 5.2.4 on 2025-08-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_member_company_projects_member_project_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedanTVVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Video title', max_length=200)),
                ('youtube_url', models.URLField(help_text='Full YouTube video URL (e.g., https://www.youtube.com/watch?v=dQw4w9WgXcQ)')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this video on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Redan TV Video',
                'verbose_name_plural': 'Redan TV Videos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
